<a href="https://colab.research.google.com/github/tsewangnamgail/ML-DL/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#one dimentional array

In [ ]:
import numpy as np
List =[2,3,4,5,6]
arr=np.array(List)
type(arr)

numpy.ndarray

In [ ]:
arr
arr.shape

(5,)

#two dimentional arry

In [ ]:
l1=[1,2,3,5,6]
l2=[4,5,6,8,4]
l3=[7,8,9,6,7]
arr=np.array([l1,l2,l3])
print(arr.shape)
arr[0,3]=56   # changing an element in an np array
print(arr)

(3, 5)
[[ 1  2  3 56  6]
 [ 4  5  6  8  4]
 [ 7  8  9  6  7]]


In [ ]:
arr.reshape(5,3)

array([[1, 2, 3],
       [5, 6, 4],
       [5, 6, 8],
       [4, 7, 8],
       [9, 6, 7]])

In [ ]:
print(arr[0:2,0:2])
print(arr[1:3,3:6])

[[1 2]
 [4 5]]
[[8 4]
 [6 7]]


In [ ]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
#copy function
arr[3:]=100
print(arr)
print(arr*2)


[  0   2   4 100 100]
[  0   4   8 200 200]


In [ ]:
#random
print(np.random.rand(3,3))
print(np.random.randn(3,3))

[[0.32777666 0.09460759 0.92813984]
 [0.5750373  0.43034795 0.7127463 ]
 [0.0451365  0.01267985 0.45698168]]
[[ 1.56559017 -0.29978133  0.71232339]
 [-1.71515103  1.27131153  1.40407376]
 [ 1.05833545  0.07955124  0.02567204]]


In [ ]:
np.random.randint(0,100,8).reshape(2,4)

array([[74, 40, 90, 91],
       [40, 21, 77,  8]])

# numpy conversion


In [ ]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
zeros =np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace=np.linspace(1,5,12)
lspace

TypeError: 'tuple' object is not callable

In [ ]:
emp= np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
ide=np.identity(45)
print(ide)
print(ide.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(45, 45)


In [ ]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()  # makes it one d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

#axis

In [ ]:
# 1D=(axis=0)only
# 2D=(axis=0(rowa))and (axis=1(coulmn))

In [ ]:
x=[[1,2,3],[4,5,6],[7,1,0]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[12  8  9]
[ 6 15  8]


In [ ]:
arr.T   #it will make my array trandspoce

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
arr.flat
for item in arr.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
arr.ndim  #it shows number of dimensioin

2

In [ ]:
arr.nbytes     #total bytes consume

72

In [ ]:
print(arr.argmin())
print(arr.argmax())

8
6


In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
print(arr.argmax(axis=0))  #max in column
print(arr.argmin(axis=1)) #max in rows

array([2, 1, 1])

In [ ]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
one=np.array([2,1,4,666,6])
print(one.argmax())   # gives the index of max element
print(one.argmin())

3
1


In [ ]:
one.argsort()# it will show the sorted order in index form(1D)

array([1, 0, 2, 4, 3])

In [ ]:
arr.argsort()  #in 2D

#operations

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
arr+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
arr*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
arr.sum()

29

In [ ]:
arr.max()

7

In [ ]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.count_nonzero(arr)  # count number of non zero elenent

8

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
arr[1,2]=0

In [ ]:
np.nonzero(arr)   #1,2 will be deleted

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

#size difference

In [ ]:
import sys

In [ ]:
py_ar=[0,4,55,2]

In [ ]:
np_ar=np.array(py_ar)

In [ ]:
sys.getsizeof(1)*len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size     #see the difference

32

numpy methos and attribute
https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html